kafka:
  brokers: "localhost:9092"
  topics: order-events
  group_id: "order-group"
  num_workers: 20

redis:
  address: "localhost:6379"

storage:
  main:
    host: localhost
    port: 5432
    username: user
    password: password
    dbname: dbname
    pool:
      max_connections: 500
      min_connections: 20
      max_lifetime: 3600
      max_idle_time: 300
      health_check_period: 30
    outbox_table:
      batch_size: 20
      num_workers: 5

  side:
    host: localhost
    port: 5432
    username: user
    password: password
    dbname: dbname
    pool:
      max_connections: 50
      min_connections: 20
      max_lifetime: 3600
      max_idle_time: 300
      health_check_period: 30

server:
  port: 8080
  host: 0.0.0.0

logging:
  mode:     "dev"         # dev | prod
  level:    "info"              # debug|info|warn|error|…
  encoding: "console"           # console|json

  sampling:                  # nil (off) или объект с Initial/Thereafter
    initial:    50
    thereafter: 100

  initialFields:             # любые ключи, которые попадут в каждый лог
    service: "auth"
    env:     "production"

  disableCaller: true       # true = убрать caller из логов
  disableStacktrace: true   # true = отключить stacktrace на Error+

  outputPaths:
    - "stdout"

  errorOutputPaths:
    - "stderr"

  timestampKey: "ts"         # вместо "timestamp"
  capitalizeLevel: true      # цветной, заглавный level encoder